In [1]:
import pandas as pd
import numpy as np
import sqlite3 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
cust_conn = sqlite3.connect("E-commerce & cust behaviour.db")
cust_cursor = cust_conn.cursor()

In [3]:
cust_cursor.execute('''
CREATE TABLE IF NOT EXISTS customer (
Cust_id INTEGER PRIMARY KEY,
Name TEXT,
City TEXT,
Total_orders INTEGER,
Amount REAL
)
''')

In [4]:
delete_table = 'DROP TABLE IF EXISTS customer'

In [5]:
cust_cursor.execute('''
CREATE TABLE IF NOT EXISTS customer (
Cust_id INTEGER PRIMARY KEY,
Name TEXT,
City TEXT,
Total_orders INTEGER,
Amount REAL
)
''')

In [6]:
cust_data =[
    (101,'Divya','Pune',5,10000),
    (102,'Sagar','Dhule',4,14000.20),
    (103,'Shiva','Yavat',3,12000.50),
    (104,'Nayan','Uruli',6,17000),
    (105,'Priya','Pune',5,10000),
    (106,'Kamal','Mumbai',12,80000.40),
    (107,'Pranav','Solapur',8,50000.30),
    (108,'Abhi','Bangalore',15,112000),
    (109,'Shiv','Nashik',10,100000),
    (110,'Umesh','Nagpur',12,105000.10),
    (111,'Ravi','Delhi',18,150000),
    (112,'Varun','Pune',14,120000.20),
    (113,'Vani','Bangalore',20,167000.60),
    (114,'Hema','Bangalore',15,150000),
    (115,'Karuna','Mumbai',9,102000),
    (116,'Krupa','Mumbai',16,170000)
]

In [7]:
cust_cursor.execute('DROP TABLE IF EXISTS customer')
cust_conn.commit()
print("Old table selete successfully!")

Old table selete successfully!

In [8]:
cust_cursor.execute('''
CREATE TABLE IF NOT EXISTS customer (
    Cust_id INTEGER PRIMARY KEY,
    Name TEXT,
    City TEXT,
    Total_orders INTEGER,
    Amount REAL
)
''')
cust_conn.commit()
print("New table created Successfully!")

New table created Successfully!

In [9]:
cust_cursor.executemany('INSERT OR IGNORE INTO customer VALUES(?,?,?,?,?)', cust_data)
cust_conn.commit()

In [10]:
df = "SELECT * FROM customer"

In [11]:
result= pd.read_sql(df,cust_conn)

In [12]:
result

    Cust_id    Name       City  Total_orders    Amount
0       101   Divya       Pune             5   10000.0
1       102   Sagar      Dhule             4   14000.2
2       103   Shiva      Yavat             3   12000.5
3       104   Nayan      Uruli             6   17000.0
4       105   Priya       Pune             5   10000.0
5       106   Kamal     Mumbai            12   80000.4
6       107  Pranav    Solapur             8   50000.3
7       108    Abhi  Bangalore            15  112000.0
8       109    Shiv     Nashik            10  100000.0
9       110   Umesh     Nagpur            12  105000.1
10      111    Ravi      Delhi            18  150000.0
11      112   Varun       Pune            14  120000.2
12      113    Vani  Bangalore            20  167000.6
13      114    Hema  Bangalore            15  150000.0
14      115  Karuna     Mumbai             9  102000.0
15      116   Krupa     Mumbai            16  170000.0

In [13]:
#task 1 Write an SQL query to retrieve all columns from the customer table where the Amount is greater than 100000.

In [14]:
high_amt = "SELECT * FROM customer WHERE Amount > 100000"

In [15]:
result1 = pd.read_sql(high_amt,cust_conn)
result1

   Cust_id    Name       City  Total_orders    Amount
0      108    Abhi  Bangalore            15  112000.0
1      110   Umesh     Nagpur            12  105000.1
2      111    Ravi      Delhi            18  150000.0
3      112   Varun       Pune            14  120000.2
4      113    Vani  Bangalore            20  167000.6
5      114    Hema  Bangalore            15  150000.0
6      115  Karuna     Mumbai             9  102000.0
7      116   Krupa     Mumbai            16  170000.0

In [16]:
#Task 2 Write an SQL query to retrieve all columns from the customer table and sort the dataset based on Total_orders in descending order (highest to lowest).

In [17]:
total_orders = "SELECT * FROM customer ORDER BY Total_orders DESC"

In [18]:
result2 = pd.read_sql(total_orders,cust_conn)
result2

    Cust_id    Name       City  Total_orders    Amount
0       113    Vani  Bangalore            20  167000.6
1       111    Ravi      Delhi            18  150000.0
2       116   Krupa     Mumbai            16  170000.0
3       108    Abhi  Bangalore            15  112000.0
4       114    Hema  Bangalore            15  150000.0
5       112   Varun       Pune            14  120000.2
6       106   Kamal     Mumbai            12   80000.4
7       110   Umesh     Nagpur            12  105000.1
8       109    Shiv     Nashik            10  100000.0
9       115  Karuna     Mumbai             9  102000.0
10      107  Pranav    Solapur             8   50000.3
11      104   Nayan      Uruli             6   17000.0
12      101   Divya       Pune             5   10000.0
13      105   Priya       Pune             5   10000.0
14      102   Sagar      Dhule             4   14000.2
15      103   Shiva      Yavat             3   12000.5

In [19]:
#Task 3 Write an SQL query to retrieve all columns from the customer table, but only return the Top 3 customers who have the highest number of Total_orders.

In [20]:
top3 = "SELECT * FROM customer ORDER BY Total_orders DESC LIMIT 3"

In [21]:
result3 = pd.read_sql(top3,cust_conn)
result3

   Cust_id   Name       City  Total_orders    Amount
0      113   Vani  Bangalore            20  167000.6
1      111   Ravi      Delhi            18  150000.0
2      116  Krupa     Mumbai            16  170000.0

In [22]:
#Task 4 Write an SQL query to retrieve all columns from the customer table where the City is equal to 'Pune' AND the Total_orders are greater than 5.

In [23]:
City = "SELECT * FROM customer WHERE City = 'Pune' AND Total_orders >5"

In [24]:
result4 = pd.read_sql(City,cust_conn)
result4

   Cust_id   Name  City  Total_orders    Amount
0      112  Varun  Pune            14  120000.2

In [25]:
#Task 5 Write an SQL query to retrieve all columns from the customer table where the City is equal to 'Mumbai' OR the City is equal to 'Delhi'.

In [26]:
City = "SELECT * FROM customer WHERE City = 'Mumbai' OR City = 'Delhi'"

In [27]:
result5 = pd.read_sql(City,cust_conn)
result5

   Cust_id    Name    City  Total_orders    Amount
0      106   Kamal  Mumbai            12   80000.4
1      111    Ravi   Delhi            18  150000.0
2      115  Karuna  Mumbai             9  102000.0
3      116   Krupa  Mumbai            16  170000.0

In [28]:
#Task 6 Write an SQL query to retrieve all columns from the customer table where the City is in either 'Pune', 'Mumbai', or 'Delhi'. Optimize this query by using the IN operator.

In [29]:
city = "SELECT * FROM customer WHERE City IN ('Pune', 'Mumbai','Delhi')"

In [30]:
result6 = pd.read_sql(city,cust_conn)
result6

   Cust_id    Name    City  Total_orders    Amount
0      101   Divya    Pune             5   10000.0
1      105   Priya    Pune             5   10000.0
2      106   Kamal  Mumbai            12   80000.4
3      111    Ravi   Delhi            18  150000.0
4      112   Varun    Pune            14  120000.2
5      115  Karuna  Mumbai             9  102000.0
6      116   Krupa  Mumbai            16  170000.0

In [31]:
#Task 7 Write an SQL query to retrieve all columns from the customer table where the Amount is between 50000 and 150000 (inclusive of both values). Optimize this query using the BETWEEN operator.

In [32]:
amt = "SELECT * FROM customer WHERE Amount BETWEEN 50000 and 150000"

In [33]:
result7 = pd.read_sql(amt,cust_conn)
result7

   Cust_id    Name       City  Total_orders    Amount
0      106   Kamal     Mumbai            12   80000.4
1      107  Pranav    Solapur             8   50000.3
2      108    Abhi  Bangalore            15  112000.0
3      109    Shiv     Nashik            10  100000.0
4      110   Umesh     Nagpur            12  105000.1
5      111    Ravi      Delhi            18  150000.0
6      112   Varun       Pune            14  120000.2
7      114    Hema  Bangalore            15  150000.0
8      115  Karuna     Mumbai             9  102000.0

In [34]:
#task 8 Write an SQL query to retrieve all columns from the customer table where the customer's Name starts with the letter 'P'. Optimize this query using the LIKE operator.

In [35]:
name = "SELECT * FROM customer WHERE Name LIKE 'P%'"

In [36]:
result8 = pd.read_sql(name,cust_conn)
result8

   Cust_id    Name     City  Total_orders   Amount
0      105   Priya     Pune             5  10000.0
1      107  Pranav  Solapur             8  50000.3

In [37]:
#task 9 Write an SQL query to retrieve all columns from the customer table where the customer's Name ends with the letter 'a'. Optimize this query using the LIKE operator.

In [38]:
name = "SELECT * FROM customer WHERE Name LIKE '%a'"

In [39]:
result9 = pd.read_sql(name,cust_conn)
result9

   Cust_id    Name       City  Total_orders    Amount
0      101   Divya       Pune             5   10000.0
1      103   Shiva      Yavat             3   12000.5
2      105   Priya       Pune             5   10000.0
3      114    Hema  Bangalore            15  150000.0
4      115  Karuna     Mumbai             9  102000.0
5      116   Krupa     Mumbai            16  170000.0

In [40]:
#task 10 Write an SQL query to retrieve all columns from the customer table where the customer's Name contains the letter 'v' (anywhere in the name). Optimize this query using the LIKE operator.

In [41]:
name = "SELECT * FROM customer WHERE Name LIKE '%v%'"

In [42]:
result10 = pd.read_sql(name,cust_conn)
result10

   Cust_id    Name       City  Total_orders    Amount
0      101   Divya       Pune             5   10000.0
1      103   Shiva      Yavat             3   12000.5
2      107  Pranav    Solapur             8   50000.3
3      109    Shiv     Nashik            10  100000.0
4      111    Ravi      Delhi            18  150000.0
5      112   Varun       Pune            14  120000.2
6      113    Vani  Bangalore            20  167000.6

In [43]:
#task 11 Write an SQL query to calculate the total sum of the Amount column and the total number of rows (customers) in the customer table. Optimize this query using SUM() and COUNT() functions.

In [44]:
count = "SELECT SUM(Amount) AS 'Total', COUNT(Name) AS 'Total_customer' FROM customer"

In [45]:
result11 = pd.read_sql(count,cust_conn)
result11

       Total  Total_customer
0  1369002.3              16

In [46]:
#task 12 Write an SQL query to find the average Amount spent by customers in each City. Display the City name alongside the average amount, and group the results by City. Optimize this query using AVG() and GROUP BY.

In [47]:
details = "SELECT City, AVG(Amount) AS 'Average_amt_spent_by_customer'FROM customer GROUP BY City"

In [48]:
result12 = pd.read_sql(details,cust_conn)
result12

        City  Average_amt_spent_by_customer
0  Bangalore                  143000.200000
1      Delhi                  150000.000000
2      Dhule                   14000.200000
3     Mumbai                  117333.466667
4     Nagpur                  105000.100000
5     Nashik                  100000.000000
6       Pune                   46666.733333
7    Solapur                   50000.300000
8      Uruli                   17000.000000
9      Yavat                   12000.500000

In [49]:
#task13 Write an SQL query to find the average Amount spent by customers in each City, but only display those cities where the average amount is greater than 80000. Optimize this query using GROUP BY and HAVING.

In [50]:
highavgamt_city = "SELECT City, AVG(Amount) AS 'Average_amt_spent_by_customer'FROM customer GROUP BY CITY HAVING Average_amt_spent_by_customer > 80000"

In [51]:
result13 = pd.read_sql(highavgamt_city,cust_conn)
result13

        City  Average_amt_spent_by_customer
0  Bangalore                  143000.200000
1      Delhi                  150000.000000
2     Mumbai                  117333.466667
3     Nagpur                  105000.100000
4     Nashik                  100000.000000

In [52]:
#TASK14 Write an SQL query to retrieve the Name and City from the customer table, and the corresponding Order_date from the orders table. Join both tables using an INNER JOIN based on the common column Cust_id.

In [53]:
cust_cursor.execute('''
CREATE TABLE IF NOT EXISTS orders (
order_date NOT NULL
)
''')

In [54]:
order_data = [
    (101, '2026-05-01'),
    (103, '2026-05-02'),
    (105, '2026-05-03'),
    (106, '2026-05-04'),
    (107, '2026-05-05'),
    (108, '2026-05-06'),
    (109, '2026-05-07'),
    (110, '2026-05-08'),
    (111, '2026-05-09'),
    (112, '2026-05-10'),
    (113, '2026-05-11'),
    (114, '2026-05-12'),
    (115, '2026-05-13'),
    (116, '2026-05-14'),
    (106, '2026-05-15'),
    (111, '2026-05-16')
]

In [55]:
cust_cursor.execute("DROP TABLE IF EXISTS orders")

In [56]:
cust_cursor.execute('''
CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY AUTOINCREMENT,
    Cust_id INTEGER NOT NULL,
    order_date TEXT NOT NULL
)
''')

In [57]:
order_data = [
    (101, '2026-05-01'),
    (103, '2026-05-02'),
    (105, '2026-05-03'),
    (106, '2026-05-04'),
    (107, '2026-05-05'),
    (108, '2026-05-06'),
    (109, '2026-05-07'),
    (110, '2026-05-08'),
    (111, '2026-05-09'),
    (112, '2026-05-10'),
    (113, '2026-05-11'),
    (114, '2026-05-12'),
    (115, '2026-05-13'),
    (116, '2026-05-14'),
    (106, '2026-05-15'),
    (111, '2026-05-16')
]

In [58]:
cust_cursor.executemany('INSERT INTO orders (Cust_id, order_date) VALUES (?, ?)', order_data)
cust_conn.commit()

In [59]:
#Task 14 Write an SQL query to retrieve the Name and City from the customer table, and the corresponding Order_date from the orders table. Join both tables using an INNER JOIN based on the common column Cust_id.

In [60]:
join = """
SELECT customer.NAME,customer.City, orders.order_date FROM customer
INNER JOIN orders ON orders.Cust_id = customer.Cust_id;
"""

In [61]:
join_result14 = pd.read_sql(join,cust_conn)
join_result14

      Name       City  order_date
0    Divya       Pune  2026-05-01
1    Shiva      Yavat  2026-05-02
2    Priya       Pune  2026-05-03
3    Kamal     Mumbai  2026-05-04
4   Pranav    Solapur  2026-05-05
5     Abhi  Bangalore  2026-05-06
6     Shiv     Nashik  2026-05-07
7    Umesh     Nagpur  2026-05-08
8     Ravi      Delhi  2026-05-09
9    Varun       Pune  2026-05-10
10    Vani  Bangalore  2026-05-11
11    Hema  Bangalore  2026-05-12
12  Karuna     Mumbai  2026-05-13
13   Krupa     Mumbai  2026-05-14
14   Kamal     Mumbai  2026-05-15
15    Ravi      Delhi  2026-05-16

In [62]:
limit = "SELECT * FROM customer LIMIT 3"

In [63]:
result = pd.read_sql(limit,cust_conn)
result

   Cust_id   Name   City  Total_orders   Amount
0      101  Divya   Pune             5  10000.0
1      102  Sagar  Dhule             4  14000.2
2      103  Shiva  Yavat             3  12000.5

In [64]:
df = "SELECT * FROM customer WHERE City IN ('Pune','Mumbai','Yavat')"

In [65]:
result1 = pd.read_sql(df,cust_conn)
result1

   Cust_id    Name    City  Total_orders    Amount
0      101   Divya    Pune             5   10000.0
1      103   Shiva   Yavat             3   12000.5
2      105   Priya    Pune             5   10000.0
3      106   Kamal  Mumbai            12   80000.4
4      112   Varun    Pune            14  120000.2
5      115  Karuna  Mumbai             9  102000.0
6      116   Krupa  Mumbai            16  170000.0

In [66]:
#Task 15 (Part A) Write an SQL query to retrieve the Name and City from the customer table, and the corresponding order_date from the orders table. Join both tables using a LEFT JOIN based on the common column Cust_id so that all customers are displayed.

In [67]:
join = """ 
SELECT customer.Name,customer.City, orders.order_date from customer
LEFT JOIN orders ON customer.Cust_id = orders.Cust_id
"""

In [68]:
result15 = pd.read_sql(join,cust_conn)
result15

      Name       City  order_date
0    Divya       Pune  2026-05-01
1    Sagar      Dhule        None
2    Shiva      Yavat  2026-05-02
3    Nayan      Uruli        None
4    Priya       Pune  2026-05-03
5    Kamal     Mumbai  2026-05-04
6    Kamal     Mumbai  2026-05-15
7   Pranav    Solapur  2026-05-05
8     Abhi  Bangalore  2026-05-06
9     Shiv     Nashik  2026-05-07
10   Umesh     Nagpur  2026-05-08
11    Ravi      Delhi  2026-05-09
12    Ravi      Delhi  2026-05-16
13   Varun       Pune  2026-05-10
14    Vani  Bangalore  2026-05-11
15    Hema  Bangalore  2026-05-12
16  Karuna     Mumbai  2026-05-13
17   Krupa     Mumbai  2026-05-14

In [69]:
#Task 16 Write an SQL query to retrieve the Name and City from the customer table, along with the total count of orders placed by each customer. Combine LEFT JOIN with GROUP BY and COUNT(orders.order_date) so that even customers with zero orders are displayed with a count of 0.

In [70]:
report = """
SELECT customer.Name,customer.City,COUNT(orders.Order_date) AS 'Total_orders' FROM customer
LEFT JOIN orders ON customer.Cust_id = orders.Cust_id
GROUP BY customer.Cust_id;
"""

In [71]:
result16 = pd.read_sql(report,cust_conn)
result16

      Name       City  Total_orders
0    Divya       Pune             1
1    Sagar      Dhule             0
2    Shiva      Yavat             1
3    Nayan      Uruli             0
4    Priya       Pune             1
5    Kamal     Mumbai             2
6   Pranav    Solapur             1
7     Abhi  Bangalore             1
8     Shiv     Nashik             1
9    Umesh     Nagpur             1
10    Ravi      Delhi             2
11   Varun       Pune             1
12    Vani  Bangalore             1
13    Hema  Bangalore             1
14  Karuna     Mumbai             1
15   Krupa     Mumbai             1

In [72]:
#Task 17 Write an SQL query to retrieve the Name, City, and total count of orders for each customer (exactly like Task 16), but sort the final output in descending order based on the Total_orders column. This will display your top-performing customers at the very top of the report.

In [73]:
result1 = """
SELECT customer.Name,customer.City,COUNT(orders.order_date) AS 'Total_Orders' FROM customer
LEFT JOIN orders ON customer.Cust_id = orders.Cust_id
GROUP BY customer.Cust_id
ORDER BY Total_Orders DESC;
"""

In [74]:
result17 = pd.read_sql(result1,cust_conn)
result17

      Name       City  Total_Orders
0    Kamal     Mumbai             2
1     Ravi      Delhi             2
2    Divya       Pune             1
3    Shiva      Yavat             1
4    Priya       Pune             1
5   Pranav    Solapur             1
6     Abhi  Bangalore             1
7     Shiv     Nashik             1
8    Umesh     Nagpur             1
9    Varun       Pune             1
10    Vani  Bangalore             1
11    Hema  Bangalore             1
12  Karuna     Mumbai             1
13   Krupa     Mumbai             1
14   Sagar      Dhule             0
15   Nayan      Uruli             0

In [75]:
#Task 18 Write an SQL query to retrieve the Name, City, and total count of orders for each customer (exactly like Task 17). However, filter the final output to display only those customers who have placed more than 1 order (i.e., Total_Orders > 1). Use the HAVING clause right after the GROUP BY clause to apply this aggregate filter.

In [76]:
result2 = """
SELECT customer.Name,customer.City,COUNT(orders.order_date) AS 'Total_orders' FROM customer
LEFT JOIN orders ON customer.Cust_id = orders.Cust_id
GROUP BY customer.Cust_id
HAVING COUNT(orders.order_date) > 1
ORDER BY Total_Orders DESC;
"""

In [77]:
result18 = pd.read_sql(result2,cust_conn)
result18

    Name    City  Total_orders
0  Kamal  Mumbai             2
1   Ravi   Delhi             2

In [78]:
#Task 19 Write an SQL query to retrieve the Name and City from the customer table for all customers who have placed at least one order. However, instead of using a JOIN, complete this task using a Subquery with the IN operator (filtering customer.Cust_id against the list of IDs present in the orders table). Sorting the output is optional.

In [79]:
subquery = "SELECT Name,City from customer WHERE Cust_id IN (SELECT Cust_id FROM orders)"

In [80]:
result19 = pd.read_sql(subquery,cust_conn)
result19

      Name       City
0    Divya       Pune
1    Shiva      Yavat
2    Priya       Pune
3    Kamal     Mumbai
4   Pranav    Solapur
5     Abhi  Bangalore
6     Shiv     Nashik
7    Umesh     Nagpur
8     Ravi      Delhi
9    Varun       Pune
10    Vani  Bangalore
11    Hema  Bangalore
12  Karuna     Mumbai
13   Krupa     Mumbai

In [81]:
#Task 20 Write an SQL query to retrieve the Name and City of customers who have never placed any order, using a subquery with the NOT IN operator.

In [82]:
subquery2 = "SELECT Name,City FROM customer WHERE Cust_id NOT IN (SELECT Cust_id FROM orders)"

In [83]:
result20 = pd.read_sql(subquery2,cust_conn)
result20

    Name   City
0  Sagar  Dhule
1  Nayan  Uruli

In [84]:
#Task 21 Write an SQL query to retrieve all columns from the orders table for customers who live in the city of 'Pune', using a subquery.

In [85]:
subquery3 = "SELECT * FROM orders WHERE Cust_id IN (SELECT Cust_id FROM customer WHERE City = 'Pune')"

In [86]:
result21 = pd.read_sql(subquery3,cust_conn)
result21

   order_id  Cust_id  order_date
0         1      101  2026-05-01
1         3      105  2026-05-03
2        10      112  2026-05-10

In [87]:
#Task 22 Write an SQL query to find the Name of all customers who live in the same city as 'Kamal' (excluding Kamal himself), using a subquery.

In [88]:
subquery4 = "SELECT Name FROM customer WHERE City = (SELECT City FROM customer WHERE Name = 'Kamal') AND Name != 'Kamal'"

In [89]:
result21 = pd.read_sql(subquery4,cust_conn)
result21

     Name
0  Karuna
1   Krupa

In [90]:
#Task 23 Write an SQL query to retrieve all details from the orders table where the order amount is greater than the average order amount of all orders, using a subquery with the AVG() function.

In [91]:
subquery5 = """
SELECT * FROM customer WHERE Amount > (SELECT AVG(Amount) FROM customer);
"""

In [92]:
result23 = pd.read_sql(subquery5,cust_conn)
result23

   Cust_id    Name       City  Total_orders    Amount
0      108    Abhi  Bangalore            15  112000.0
1      109    Shiv     Nashik            10  100000.0
2      110   Umesh     Nagpur            12  105000.1
3      111    Ravi      Delhi            18  150000.0
4      112   Varun       Pune            14  120000.2
5      113    Vani  Bangalore            20  167000.6
6      114    Hema  Bangalore            15  150000.0
7      115  Karuna     Mumbai             9  102000.0
8      116   Krupa     Mumbai            16  170000.0

In [93]:
#Task 24 Write an SQL query to find the Name and City of customers who placed an order on the most recent (MAX) order date, using a subquery.

In [94]:
subquery6 = "SELECT Name, City FROM customer WHERE Cust_id IN (SELECT Cust_id FROM orders WHERE order_date = (SELECT MAX(order_date) FROM orders))"

In [95]:
result24 = pd.read_sql(subquery6,cust_conn)
result24

   Name   City
0  Ravi  Delhi

In [96]:
#Task 25: "Write an SQL query to retrieve all order details (order_id, order_date) along with the matching customer's Name and City using a RIGHT JOIN logic, ensuring that all records from the orders table are preserved even if the customer details are missing."

In [97]:
right_join_query = """
SELECT customer.Name,customer.City, orders.order_id, orders.order_date FROM orders
LEFT JOIN customer ON orders.Cust_id = customer.Cust_id;
"""

In [98]:
result15 = pd.read_sql(right_join_query,cust_conn)
result15

      Name       City  order_id  order_date
0    Divya       Pune         1  2026-05-01
1    Shiva      Yavat         2  2026-05-02
2    Priya       Pune         3  2026-05-03
3    Kamal     Mumbai         4  2026-05-04
4   Pranav    Solapur         5  2026-05-05
5     Abhi  Bangalore         6  2026-05-06
6     Shiv     Nashik         7  2026-05-07
7    Umesh     Nagpur         8  2026-05-08
8     Ravi      Delhi         9  2026-05-09
9    Varun       Pune        10  2026-05-10
10    Vani  Bangalore        11  2026-05-11
11    Hema  Bangalore        12  2026-05-12
12  Karuna     Mumbai        13  2026-05-13
13   Krupa     Mumbai        14  2026-05-14
14   Kamal     Mumbai        15  2026-05-15
15    Ravi      Delhi        16  2026-05-16

In [99]:
#Task26 "Write an SQL query to list all orders showing order_id and Cust_id from the orders table, along with the customer's Name from the customer table. Use the RIGHT JOIN logic (Table Swapping) to ensure that every single order is displayed in the output, even if a customer's name is not found."

In [100]:
right_join_query2 = """
SELECT customer.Name, customer.Cust_id, orders.order_id FROM orders
LEFT JOIN customer ON customer.Cust_id = orders.Cust_id;
"""

In [101]:
result26 = pd.read_sql(right_join_query2,cust_conn)
result26

      Name  Cust_id  order_id
0    Divya      101         1
1    Shiva      103         2
2    Priya      105         3
3    Kamal      106         4
4   Pranav      107         5
5     Abhi      108         6
6     Shiv      109         7
7    Umesh      110         8
8     Ravi      111         9
9    Varun      112        10
10    Vani      113        11
11    Hema      114        12
12  Karuna      115        13
13   Krupa      116        14
14   Kamal      106        15
15    Ravi      111        16

In [102]:
#Task27 The marketing team wants to create a clean, automated summary string for each customer to use in their upcoming promotional campaign reports.Write an SQL query using the customer table to merge text and column values into a single formatted sentenc

In [103]:
string_query = "SELECT Name, City, Name || ' From ' || City AS 'Customer_details' FROM customer "

In [104]:
result27 = pd.read_sql(string_query,cust_conn)
result27

      Name       City     Customer_details
0    Divya       Pune      Divya From Pune
1    Sagar      Dhule     Sagar From Dhule
2    Shiva      Yavat     Shiva From Yavat
3    Nayan      Uruli     Nayan From Uruli
4    Priya       Pune      Priya From Pune
5    Kamal     Mumbai    Kamal From Mumbai
6   Pranav    Solapur  Pranav From Solapur
7     Abhi  Bangalore  Abhi From Bangalore
8     Shiv     Nashik     Shiv From Nashik
9    Umesh     Nagpur    Umesh From Nagpur
10    Ravi      Delhi      Ravi From Delhi
11   Varun       Pune      Varun From Pune
12    Vani  Bangalore  Vani From Bangalore
13    Hema  Bangalore  Hema From Bangalore
14  Karuna     Mumbai   Karuna From Mumbai
15   Krupa     Mumbai    Krupa From Mumbai

In [105]:
#task 28 The inventory department sent a new item category, but due to a technical glitch, the text has a lot of accidental spaces: '      Data Analytics Tools      '. We need to clean this text and format it into a neat label for our dashboard.
#Write an SQL query to clean the text and create a professional report label.

In [106]:
trim_query = " SELECT 'Course : ' ||TRIM('     Data Analytics Tools    ') AS formatted_course_label"

In [107]:
result28 = pd.read_sql(trim_query,cust_conn)
result28

          formatted_course_label
0  Course : Data Analytics Tools

In [108]:
#Task 29 The operations team noticed that in our location master, some entries for the city of 'Bangalore' need to be officially updated to its new name 'Bengaluru' for the upcoming reports.
#Write a standalone SQL query to transform the city name using the REPLACE() function.

In [109]:
replace_query = " SELECT REPLACE('Welcome to Bangalore', 'Bangalore', 'Bengaluru') AS 'New_Sentence'"

In [110]:
result29 =pd.read_sql(replace_query,cust_conn)
result29

           New_Sentence
0  Welcome to Bengaluru

In [111]:
#task30 The product inventory team has generated some automated tracking codes formatted like this: 'PROD-9942'. For the new clean inventory report, the manager only wants to display the numeric extension part (the number '9942') by cutting out the prefix.
#Write a standalone SQL query to extract a specific portion of a text string using the SUBSTR() function.

In [112]:
substr_query = "SELECT SUBSTR('PROD-9942',6,4) AS 'Extracted_Product_Number'"

In [113]:
result30 =pd.read_sql(substr_query,cust_conn)
result30

  Extracted_Product_Number
0                     9942

In [114]:
#Task31 The HR department exported some employee data from an old legacy system, but the location codes are very messy and contain corrupted prefixes and spaces, like this: '   EMP-ID: 2026_MUMBAI   '. The HR manager wants a clean, polished label on the dashboard.
#Write a standalone SQL query using nested functions to clean the text and transform it into a professional report title.

In [117]:
nested_query = """
SELECT 'Employee City: ' || SUBSTR(TRIM('   EMP-ID: 2026_MUMBAI   '), 14, 6) AS Final_HR_Report;
"""

In [119]:
result31 = pd.read_sql(nested_query,cust_conn)
result31

         Final_HR_Report
0  Employee City: MUMBAI

In [120]:
replace_nested_query = """
SELECT 'Employee City: ' || REPLACE(TRIM('   EMP-ID: 2026_MUMBAI   '), 'EMP-ID: 2026_', '') AS Final_HR_Report;
"""
result31_alt = pd.read_sql(replace_nested_query, cust_conn)
result31_alt

         Final_HR_Report
0  Employee City: MUMBAI

## 📌 Project 4: Conclusion & Key Insights

### 📊 Business Insights Delivered
Through this **E-Commerce & Customer Behavior Analytics** project, we successfully analyzed structured retail data to extract actionable insights:
* **Customer Segmentation:** Identified high-value customers based on their purchase history and geographical locations to assist the marketing team in targeted campaigns.
* **Data Cleaning & Standardization:** Addressed technical glitches in the legacy location and product data by removing accidental whitespaces and formatting corrupted structural codes.

---

### 🛠️ Technical Skills Demonstrated
This project showcases robust end-to-end data manipulation capabilities using **SQL (SQLite)** and **Python (Pandas)**:
1. **Advanced String Manipulation:** Applied `TRIM()`, `REPLACE()`, and `SUBSTR()` to standardize and clean messy user-generated entries.
2. **String Concatenation:** Utilized the `||` operator to build custom, automated profile summaries and report labels (e.g., generating dynamically formatted customer communication text).
3. **Data Integration:** Implemented complex `JOIN` operations and aggregation functions to bridge disparate customer metrics into unified analytical DataFrames.
4. **Standalone & Nested Testing:** Designed efficient nested queries executing sequential logic (Inside-Out approach) without relying on permanent database tables.

---

### 🚀 Final Takeaway
The database has been fully optimized and cleaned. The queries developed in this project directly support business intelligence operations, ensuring that the promotional campaign reports are backed by 100% accurate, standardized, and clean customer data.